service: cen3031-backend

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  stackTags:
    SITE: ${self:service}-${self:provider.stage}
  tags:
    SITE: ${self:service}-${self:provider.stage}
  environment: 
    REGION: ${self:provider.region}
    KEYEXAMPLE: ${env:KEYEXAMPLE}
    # AWS_BUSINESSTABLEID: ${self:service}-${self:provider.stage}-${self:provider.region}-businesses
    TASK_TABLE:
      Ref: taskTable

  lambdaHashingVersion: 20201221
  httpApi:
    cors: true

functions:
  hello:
    handler: src/handler.hello
    events:
     - httpApi:
        path: /hello
        method: get
  getRequest:
    handler: src/handler.getRequest
    events:
     - httpApi:
        path: /{name}
        method: get
        request: 
          parameters: 
            paths: 
              name: true
  createTask:
    handler: src/handler.createTask
    events:
      - httpApi:
        path: /createTask
        method: POST

package:
  exclude:
    - node_modules/aws-sdk/**
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

resources:
  Resources:
    taskTable:
      Type: AWS::DynamoDB::Table
        Properties:
        TableName: taskTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5